### PR TITLE
Fix regression that caused .pdata sections to be emitted only for ARM64 builds

### LINKED ISSUE #27: Cannot unwind stack for x64 version of the toolchain
If you build this toolchain for x64 the [test-pdata](https://github.com/ZacWalk/mingw-woarm64-build/blob/main/tests/test-pdata.c) test fails. Seems like the function entry cannot be found. This is a regression, probably in our SEH code. x64 and aarch64 use the same code to generate xdata or pdata sections with some if conditions. Something must be broken there for x64 as test-pdata does work for aarch64.

### PR DESCRIPTION
**Pull request by movediedi**
Fix regression that caused .pdata sections to be emitted only for ARM64 builds.  Sanity-tested the fix on both x64 and ARM64 builds of test-pdata.exe.

### CODE REVIEW

File: gas/config/obj-coff-seh.c [hunk 1]
```diff
@@ -1799,4 +1795,13 @@ write_function_pdata (seh_context *c)
...
 
   subseg_set (save_seg, save_subseg);
-}
\ No newline at end of file
+}
+
+static inline bool
+write_pdata_xdata_records(void)
+{
+  if (seh_get_target_kind () == seh_kind_arm64 && seh_ctx_cur->arm64_ctx.unwind_codes_byte_count == 0)
```
Comment (Blackhex) [inline gas/config/obj-coff-seh.c]: You can just return the expression value instead of using `if`.

File: gas/config/obj-coff-seh.c [hunk 2]
```diff
@@ -1799,4 +1795,13 @@ write_function_pdata (seh_context *c)
     }
 
   subseg_set (save_seg, save_subseg);
-}
\ No newline at end of file
+}
+
+static inline bool
+write_pdata_xdata_records(void)
```
Comment (Blackhex) [inline gas/config/obj-coff-seh.c:1801]: Is the most logical placement of the function within the file? Can you please explain the logic behind it?

**Review by Blackhex — COMMENTED** [review]
I see the merrit of the fix is in changing `seh_ctx_cur->arm64_ctx.unwind_codes_byte_count > 0` to `seh_ctx_cur->arm64_ctx.unwind_codes_byte_count == 0` which should be safe in regards of other targets, the rest is just code style improvement I am inviting. I am happy to approve once https://github.com/ZacWalk/mingw-woarm64-build/actions/runs/6808867666 pipeline will succeed.

File: gas/config/obj-coff-seh.c (hunk 2 above)
Comment (movediedi) [reply gas/config/obj-coff-seh.c:1801]: They have not used forward declarations in the source file for the most part and have just trusted in the order.  I was getting 'forward declaration' build errors, so I moved it to the end of the source file, but then discovered a new 'forward declaration' issue.  With that, I just added the forward declaration to resolve it.

File: gas/config/obj-coff-seh.c (hunk 1 above)
Comment (movediedi) [reply gas/config/obj-coff-seh.c]: Yes, I will have to Not the result, but I am fine with changing that.

**Review by Blackhex — APPROVED** [review]
Workflow passes, approving.

File: gas/config/obj-coff-seh.c [hunk 3]
```diff
@@ -1799,4 +1795,11 @@ write_function_pdata (seh_context *c)
...
+{
+  return !(seh_get_target_kind () == seh_kind_arm64 && seh_ctx_cur->arm64_ctx.unwind_codes_byte_count == 0);
```
Comment (ZacWalk) [inline gas/config/obj-coff-seh.c]: Nice fix, I see the problem you are solving. I wonder if this function body could be something like this to make the logic clearer:

seh_kind kind = seh_get_target_kind ();
if (kind == seh_kind_arm64)  return seh_ctx_cur->arm64_ctx.unwind_codes_byte_count > 0;
return kind == seh_kind_x64;

**Review by ZacWalk — APPROVED** [review]

**Comment by ZacWalk** [comment]
Nice fix. Merged with minor change for readability.
